apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: wordpress
    tier: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_DATABASE
          value: wordpressdb
        - name: MYSQL_USER
          value: "wordpressuser"
        - name: MYSQL_PASSWORD
          valueFrom:            
            secretKeyRef: 
              name: wp-secrets
              key: mysql_password
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          valueFrom:            
            secretKeyRef: 
              name: wp-secrets
              key: mysql_random_root_password     
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: mysql-volume
      volumes:
      - name: mysql-volume
        persistentVolumeClaim:
          claimName: mysql-pvc